version: '2.2'

services:
  # Master Node
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=es01
      - http.port=9200
      - transport.port=9301
      - network.publish_host=$SERVER1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=$SERVER1:9302, $SERVER1:9303, $SERVER2:9304, $SERVER2:9305, $SERVER2:9306
      - cluster.initial_master_nodes=$SERVER1:9301, $SERVER1:9302
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      # sets JVM heap size to 32GB, half of the physical RAM 
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
      - bootstrap.memory_lock=true
    # to disable swapping
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

    restart: "unless-stopped"

    network_mode: host

  wait_until_ready:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
      command: /usr/bin/true
      depends_on: {"es01": {"condition": "service_healthy"}}
  
  # Master Node
  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=es02
      - http.port=9202
      - transport.port=9302
      - network.publish_host=$SERVER1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=$SERVER1:9301, $SERVER1:9303, $SERVER2:9304, $SERVER2:9305, $SERVER2:9306
      - cluster.initial_master_nodes=$SERVER1:9301, $SERVER1:9302
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
      - bootstrap.memory_lock=true

    # to disable swapping
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

    restart: "unless-stopped"

    network_mode: host

  # Data Node
  es03:
    container_name: es03
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=es03
      - node.roles=data, data_content, data_hot, data_warm, data_cold, data_frozen, ingest, ml, remote_cluster_client, transform
      - http.port=9203
      - transport.port=9303
      - network.publish_host=$SERVER1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=$SERVER1:9301, $SERVER1:9302, $SERVER2:9304, $SERVER2:9305, $SERVER2:9306
      - cluster.initial_master_nodes=$SERVER1:9301, $SERVER1:9302
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es03/es03.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es03/es03.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es03/es03.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es03/es03.key
      - bootstrap.memory_lock=true

    # to disable swapping
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

    restart: "unless-stopped"

    network_mode: host

volumes:
  data01:
    driver_opts:
      type: none
      device: /home/ubuntu/elasticsearch/data01
      o: bind
  data02:
    driver_opts:
      type: none
      device: /home/ubuntu/elasticsearch/data02
      o: bind
  data03:
    driver_opts:
      type: none
      device: /home/ubuntu/elasticsearch/data03
      o: bind
  certs:
    driver_opts:
      type: none
      device: /home/ubuntu/elasticsearch/certs
      o: bind
